### PR TITLE
Implement uffd-wp support.

### PR DESCRIPTION
**Pull request by peterhuene**
This commit implements the Linux 5.7 `uffd-wp` feature that enables
protecting a range of memory pages as "write protected" and receiving
events in user space about any writes to those pages.

The `linux5_7` feature was added to enable the support.

A test was added to demonstrate how to use the feature.

### CODE REVIEW

**Comment by peterhuene** [comment]
The documentation regarding uffd-wp is, ahem, not great.  I tracked the commit that seemingly merged the feature into mainline kernel to a 5.7 tag, so I believe that's the minimum version required.

**Comment by peterhuene** [comment]
Weird, I'm running the same Ubuntu version in my VM and the kernel should be 5.8 and `_UFFDIO_WRITEPROTECT` should definitely be present in the bindgen output.

**Comment by peterhuene** [comment]
Erm wait, `ubuntu-latest` is 20.04 (5.4) and not 20.10, whoops!

**Comment by pchickey** [comment]
I just looked into this and learned that, in Debian and Ubuntu, linux headers available under the standard system search path (i.e. those in /usr/include/linux) are determined by how glibc was compiled. 

We can install the headers for a more recent kernel with `apt install linux-headers-5.8.0-49-generic` and then add `/usr/src/linux-headers-5.8.0-49-generic/include/uapi/linux` to bindgen's search path so they are picked up.

**Comment by peterhuene** [comment]
That would definitely help with at least testing the build, but it would be nice if GitHub actions offered non-LTS ubuntus to test with.

**Pull request merged**
